version: "3.2"

services:
  nginx:
    build: ./nginx
    depends_on:
      - asset-server
      - content-repo
      - frontend
      - game-client
      - game-server
      - git-json-api
    ports:
      - "80:80"
      - "443:443"

  asset-server:
    build: ./git-json-cms-asset-server
    volumes:
      - type: volume
        source: assets
        target: /var/www/webdav

  git-json-api:
    image: "artcom/git-json-api:latest"
    environment:
      REPO_URI: http://content-repo/git/content/
      PORT: 80
    depends_on:
      - content-repo

  content-repo:
    build: ./git-json-cms-content-repo
    volumes:
      - type: volume
        source: content
        target: /srv/content

  frontend:
    build:
      context: ./git-json-cms-frontend

  game-client:
    build:
      context: ./eppsa-mobile-game-client
    environment:
      PORT: 80
    depends_on:
      - game-server

  game-server:
    build:
      context: ./eppsa-mobile-game-server
    environment:
      PORT: 80

volumes:
  content:
  assets:
