version: "3.2"

services:
  nginx:
    ports:
      - "80:80"
      - "443:443"

  frontend:
    build:
      dockerfile: Dockerfile.production
    environment:
      PORT: 80

  game-client:
    build:
      dockerfile: Dockerfile.production
      args:
        WS_SERVER_PATH: /server

  game-server:
    build:
      dockerfile: Dockerfile.production
