version: "3.2"

services:
  nginx:
    ports:
      - "80:80"
      - "443:443"

  frontend:
    build:
      dockerfile: Dockerfile.development
    volumes:
      - ./git-json-cms-frontend:/app
      - /app/node_modules
    environment:
      PORT: 443

  game-client:
    build:
      dockerfile: Dockerfile.development
    volumes:
      - ./eppsa-mobile-game-client:/app
      - /app/node_modules
    environment:
      PORT: 80
      WS_SERVER_PATH: /server

  game-server:
    build:
      dockerfile: Dockerfile.development
    volumes:
      - ./eppsa-mobile-game-server:/app
      - /app/node_modules
    environment:
      PORT: 80
