version: "3.2"

services:
  nginx:
    build: ./nginx
    depends_on:
      - cms-asset-server
      - cms-content-server
      - cms-content-repo
      - cms-frontend
      - game-client
      - game-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${CERTIFICATE_PATH}:/certificate

  cms-asset-server:
    build: ./cms-asset-server
    volumes:
      - type: volume
        source: assets
        target: /var/www/webdav

  cms-content-server:
    image: "artcom/git-json-api:latest"
    environment:
      REPO_URI: http://cms-content-repo/git/content/
      PORT: 80
    depends_on:
      - cms-content-repo

  cms-content-repo:
    build: ./cms-content-repo
    volumes:
      - type: volume
        source: content
        target: /srv/content

  cms-frontend:
    build:
      context: ./cms-frontend

  game-client:
    build:
      context: ./game-client
    environment:
      PORT: 80
    depends_on:
      - game-server

  game-server:
    build:
      context: ./game-server
    environment:
      PORT: 80

volumes:
  content:
  assets:
