version: "3.2"

services:
  nginx:
    build:
      args:
        environment: production

  cms:
    build:
      dockerfile: Dockerfile.production
    environment:
      PORT: 80

  game-client:
    build:
      dockerfile: Dockerfile.production
      args:
        WS_SERVER_PATH: /game-server

  game-server:
    build:
      dockerfile: Dockerfile.production
