version: "3.2"

services:
  nginx:
    build:
      args:
        environment: development

  cms-frontend:
    build:
      dockerfile: Dockerfile.development
    volumes:
      - ./cms-frontend:/app
      - /app/node_modules
    environment:
      PORT: 443

  dashboard:
    build:
      dockerfile: Dockerfile.development
    volumes:
      - ./dashboard:/app
      - /app/node_modules

  game-client:
    build:
      dockerfile: Dockerfile.development
    volumes:
      - ./game-client:/app
      - /app/node_modules

  game-server:
    build:
      dockerfile: Dockerfile.development
    volumes:
      - ./game-server:/app
      - /app/node_modules

  mongo:
    ports:
      - "27017:27017"

  game-challenge-button:
    build:
      dockerfile: Dockerfile.development
    volumes:
      - ./game-challenge/button:/app
      - /app/node_modules

  game-challenge-hunt-client:
    build:
      dockerfile: Dockerfile.development
    volumes:
      - ./game-challenge/hunt/eppsa-mobile-game-client:/app
      - /app/node_modules
    environment:
      WS_SERVER_PATH: /server

  game-challenge-hunt-server:
    build:
      dockerfile: Dockerfile.development
    volumes:
      - ./game-challenge/hunt/eppsa-mobile-game-server:/app
      - /app/node_modules

  game-challenge-phaser-demo:
    build:
      dockerfile: Dockerfile.development
    volumes:
      - ./game-challenge/phaser-demo:/app
      - /app/node_modules

  game-challenge-quiz:
    build:
      dockerfile: Dockerfile.development
    volumes:
      - ./game-challenge/quiz:/app
      - /app/node_modules
    environment:
      PORT: 443

  game-challenge-boat:
    build:
      dockerfile: Dockerfile.development
    volumes:
      - ./game-challenge/boat:/app
      - /app/node_modules
