version: "3.2"

services:
  nginx:
    build:
      args:
        environment: production

  cms-frontend:
    build:
      dockerfile: Dockerfile.production
    environment:
      PORT: 80

  game-client:
    build:
      dockerfile: Dockerfile.production

  game-server:
    build:
      dockerfile: Dockerfile.production

  game-challenge-button:
    build:
      dockerfile: Dockerfile.production

  game-challenge-hunt-client:
    build:
      dockerfile: Dockerfile.production
      args:
        WS_SERVER_PATH: "/server"

  game-challenge-hunt-server:
    build:
      dockerfile: Dockerfile.production
