version: "3.2"

services:
  nginx:
    build: ./nginx
    depends_on:
      - asset-server
      - content-server
      - content-repo
      - cms-frontend
      - game-client
      - game-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${CERTIFICATE_PATH}:/certificate

  asset-server:
    build: ./asset-server
    volumes:
      - type: volume
        source: assets
        target: /var/www/webdav

  content-server:
    image: "artcom/git-json-api:latest"
    environment:
      REPO_URI: http://content-repo/
      PORT: 80
    depends_on:
      - content-repo

  content-repo:
    build: ./content-repo
    volumes:
      - type: volume
        source: content
        target: /srv/content

  cms-frontend:
    build:
      context: ./cms-frontend
    environment:
      GIT_JSON_API_URI: https://content-server.${HOST}
      ASSET_SERVER_URI: https://asset-server.${HOST}
    depends_on:
      - content-server
      - asset-server

  game-client:
    build:
      context: ./game-client
    environment:
      CONTENT_SERVER_URI: https://content-server.${HOST}
      ASSET_SERVER_URI: https://asset-server.${HOST}
      GAME_SERVER_URI: https://game-server.${HOST}
      PORT: 80
    depends_on:
      - content-server
      - asset-server
      - game-server

  game-server:
    build:
      context: ./game-server
    environment:
      PORT: 80
    depends_on:
      - mongo

  mongo:
    image: "mongo:3.6.3-jessie"


volumes:
  content:
  assets:
