version: "3.2"

services:
  nginx:
    build:
      args:
        environment: development

  cms-frontend:
    build:
      dockerfile: Dockerfile.development
    volumes:
      - ./cms-frontend:/app
      - /app/node_modules
    environment:
      PORT: 443

  game-client:
    build:
      dockerfile: Dockerfile.development
    volumes:
      - ./game-client:/app
      - /app/node_modules
    environment:
      WS_SERVER_PATH: /server

  game-server:
    build:
      dockerfile: Dockerfile.development
    volumes:
      - ./game-server:/app
      - /app/node_modules

  game-challenge-button:
    build:
      dockerfile: Dockerfile.development
    volumes:
      - ./game-challenge/button:/app
      - /app/node_modules
