version: "3.2"

services:
  nginx:
    build: ./nginx
    depends_on:
      - asset-server
      - content-server
      - cms
      - game-client
      - game-server
      - git-json-api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${CERTIFICATE_PATH}:/certificate

  asset-server:
    build: ./asset-server
    volumes:
      - type: volume
        source: assets
        target: /var/www/webdav

  git-json-api:
    image: "artcom/git-json-api:latest"
    environment:
      REPO_URI: http://content-server/git/content/
      PORT: 80
    depends_on:
      - content-server

  content-server:
    build: ./content-server
    volumes:
      - type: volume
        source: content
        target: /srv/content

  cms:
    build:
      context: ./cms

  game-client:
    build:
      context: ./game-client
    environment:
      PORT: 80
    depends_on:
      - server

  game-server:
    build:
      context: ./game-server
    environment:
      PORT: 80

volumes:
  content:
  assets:
